### ISSUE TITLE
Multiparent: Parent Sorting

### ISSUE THREAD

**Issue by pomodoren** [pomodoren/comorbid-graphs#15]
Allow different lambda's for updating order of parents for each node. 

```yaml
# sample.yaml
name: parent
children:
- name: node-1
  parents:
  - name: parent-1
  - name: parent-2
- name: node-2
  parents: 
  - name: parent-2 
  - name: parent-3 
name: parent-1 
name: parent-2
name: parent-3
```

Allow sorting by score.   

```python
ComorbidGraph
.load_yaml('sample.yaml')
.sort_parents(by_score=['score'])
.to_yaml('sample_ordered.yaml')
```

```yaml
# sample.yaml
name: parent
children:
- name: node-1
  score: 1
  parents:
  - name: parent-1
    score: 0.5
  - name: parent-2
    score: 0.2
- name: node-2
  score: 0.8
  parents: 
  - name: parent-2 
    score: 0.3
  - name: parent-3 
    score: 0.1
name: parent-1 
name: parent-2
name: parent-3
```

```python
ComorbidGraph
.load_yaml('sample.yaml')
.sort_parents(by_name=['parent-1', 'parent-3'])
.to_yaml('sample_ordered.yaml')
```

```yaml
# sample_ordered.yaml
name: parent
name: parent-1 
children: 
- name: node-1
  parents:
  - name: parent
  - name: parent-2
name: parent-2
name: parent-3
children: 
  name: node-2
  parents:
  - name: parent
  - name: parent-2 
```
